from .registerView import Register
from .loginView import loginView
from .usersView import UsersView
from .logoutView import LogoutView
from .listUserView import ListUserView
from .userView import UserView
from .userDetailView import UserDetail
from .clienteView import ClientesView
from .clienteEspecificoView import ClienteEspecificoView
from .pedidoView import PedidoView
from .pagoView import PagoView
from .inventarioView import InventarioView
from .productoView import ProductoView
from .productoEspecificoView import ProductoEspecificoView
from .despachoView import DespachoView
from .listaPorductosDespachoView import ProductosPedidoDespachoView
from .listaNumerosPedidosView import ListaNumerosPedidosView
from .controlProduccionView import control_produccion_agrupado
from .inventarioProductoView import InventarioPorProductoView
from .calendarioProduccionView import CalendarioProduccionView
from .calendarioEspecificoView import CalendarioEspecificoView
from .materialView import MaterialView
from .materialEspecificoView import MaterialDetailView