from .registerView import Register
from .loginView import loginView
from .usersView import UsersView
from .logoutView import LogoutView
from .listUserView import ListUserView
from .userView import UserView
from .userDetailView import UserDetail
from .clienteView import ClientesView
from .clienteEspecificoView import ClienteEspecificoView
from .pedidoView import PedidoView
from .pagoView import PagoView